### ISSUE TITLE
Shared Memory

### ISSUE THREAD

**Issue by perdelt** [Beuth-Erdelt/Benchmark-Experiment-Host-Manager#12]
for docker, like at AWS

* https://github.com/kubernetes/kubernetes/pull/63641
* https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614

**Comment by perdelt** [comment]
```
volumeMounts:
        - {mountPath: /dev/shm, name: dshm}
```
and
```
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
```
