### ISSUE TITLE
Consistent recovery state has not been yet reached at PostgreSQL

### ISSUE THREAD

**Issue by perdelt** [Beuth-Erdelt/Benchmark-Experiment-Host-Manager#253]
This happens sometimes when a persistent storage of class `shared` is used.

Is there a more graceful shutdown?

**Comment by perdelt** [comment]
Solved with
```
      terminationGracePeriodSeconds: 60
      containers:
      - name: dbms
        image: postgres:16.1
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pg_ctl stop -D /var/lib/postgresql/data -m fast"]
```
